config/routes.rb
Rails.application.routes.draw do
  root  'home#index'
  get   'home/index'    => 'home#index'
  post   'home/inquiry'  => 'home#inquiry'

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/inquiry'  => 'inquiry#inquiry'    # 送信完了画面
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def inquiry
    @inquiry = Inquiry.new(name: contactForm_params[:name], email: contactForm_params[:email], message: contactForm_params[:contactForm__message])    
    InquiryMailer.received_email(@inquiry).deliver
    flash[:notice] = 'メッセージが送信されました'
    redirect_to action: :index
  end

  private
  def contactForm_params
    params.permit(:name, :email, :contactForm__message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
  def inquiry_text
    "ご予約の方は以下のFormをご使用ください。

    【お日にち】
    ・第１希望
    ●●月●●日 ●●時●●分〜
    ・第２希望
    ●●月●●日 ●●時●●分〜
    ・第３希望
    ●●月●●日 ●●時●●分〜
    
    【コース】
    ・パーソナル15
    ・パーソナル30
    ・パーソナル40
    ・パーソナル60
    ・初回無料カウンセリング
    
    【その他要望】
    ・事前に言っておきたい事などはこちらにお書き下さい。"
  end

end

app/views/home/index.html.erb
<%= javascript_include_tag 'main' %>

<% if flash[:notice] %>
  <div class="flash time-limit font-weight-bold text-center pt-5">
    <p class="py-3 px-1 mx-auto">
      <%= flash[:notice] %><br>
      この通知は3秒後に消えます。
    </p>
  </div>
<% end %>

<header class="px-xl-5">
  <div class="d-flex justify-content-between">
    <div class="headerLeft">
      <h1 class="m-0 pl-2 pl-xl-0"><strong>M</strong>oving <strong>R</strong>ejoice <strong>T</strong>rigger</h1>
    </div>
    <div class="headerRight">
      <ul class="d-lg-flex m-0 d-none">
        <li><%= link_to "MRTとは", "#aboutUs" %></li>
        <li><%= link_to "MRT3つの柱", "#postOf3" %></li>
        <li><%= link_to "メニュー", "#menuList" %></li>
        <li><%= link_to "ご予約", "#reserv" %></li>
        <li><%= link_to "お問い合わせ", "#contactForm" %></li>
        <%# <li><a href="#aboutUs">MRTとは</a></li>
        <li><a href="#postOf3">MRT3つの柱</a></li>
        <li><a href="#menuList">メニュー</a></li>
        <li><a href="#contactForm">お問い合わせ</a></li> %>
      </ul>
      <div class="hamburgerMenu mt-2 d-lg-none mr-2 mr-xl-0">
        <p></p>
        <p></p>
        <p></p>
      </div>
    </div>
  </div>
  <!-- Ipad以下のメニュー -->
  <div class="hideMenu d-none d-lg-none"> 
    <ul class="m-0 p-0">
      <li class="pl-5"><a href="#aboutUs">MRTとは</a></li>
      <li class="pl-5"><a href="#postOf3">MRT3つの柱</a></li>
      <li class="pl-5"><a href="#menuList">メニュー</a></li>
      <li class="pl-5"><a href="#reserv">ご予約</a></li>
      <li class="pl-5"><a href="#contactForm">お問い合わせ</a></li>
    </ul>
  </div>
</header>
<!-- mainTop view-->
<div class="mainTop pl-5 d-none d-sm-block">
  <div class="mainTop__phrase">
    <h1 class="m-0 font-weight-bold">あなたには<br>あなたの方法がある。</h1>
    <h1 class="m-0 font-weight-bold pt-3">〜それぞれに合ったコンテンツを提供します〜</h1>
  </div>
</div>
<div class="mainTop pl-3 d-sm-none">
  <div class="mainTop__phrase">
    <h1 class="m-0 font-weight-bold">あなたには<br>あなたの<br>方法がある。</h1>
    <h1 class="m-0 font-weight-bold pt-3">〜それぞれに合った<br>コンテンツを提供します。〜</h1>
  </div>
</div>
<!-- mainMiddle view -->
<div class="mainMiddle">
  <!-- mainMiddle__1 view -->
  <div class="d-flex">

    <div class="mainMiddle__1 pt-5" id="aboutUs">
      <h2 class="text-center my-5 font-weight-bold">＜MRTとは、MRTの魅力＞</h2>
      <p class="text-center m-0">
        MRTとは、<strong>人生の生きがい。</strong><br>
        MRTとは、Moving Rejoice Trigger(動く、喜ぶ、キッカケ）を基盤にお客様一人一人に寄り添った個別パーソナルトレーナーです。<br>
        パフォーマンスが上がらないから楽しめない。身体が思う様にならない。
        動けない。＝楽しめない要因の１つだと感じていることがほとんどだと思います。<br>
        MRT最大の魅力はあなた一人ひとりに適するメニューを立てて通常のトレーニングから、
        メンテナンス、 人の身体に基づいた使い方指導など、幅広い視点から身体にアプローチし、動ける喜びも獲得出来ます。<br>
        <strong>結果効率的にパフォーマンスなど各自の目標に近く事ができます。</strong>
      </p>
      <div class="mainMiddle__1__youtube text-center">
        <p class="pt-5 m-0">
          管理人（アーリー）の動画です↓
          解剖学に基づいて肩痛について解説しています。
        </p>
        <iframe src="https://www.youtube.com/embed/OXQFmX4ka4Q?start=86" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>

    <div class="reserv mt-5 mx-3 d-none d-md-block pt-5">
      <p class="text-center font-weight-bold">＜ご予約はこちら↓＞</p>
      <iframe width="300" height="1100" src="https://select-type.com/rsv/?id=i9Mcxd2ZDYk&w_flg=1" frameborder="0"></iframe>
    </div>

  </div>
  <!-- mainMiddle__2 view -->
  <div class="mainMiddle__2 mt-5 pt-5 text-white" id="postOf3">
    <h2 class="text-center pt-5 font-weight-bold">＜MRT3つの柱＞</h2>
    <div class="mainMiddle__2__discription col-md-10 m-auto pt-5">
      <p class="text-center font-weight-bold">
        MRTには<strong>”3つの柱(コース)”</strong>があります。<br>
        基本的にはどれかを選ぶと言うよりはあなたとなりたい身体、その日の体調、目標などを相談しながらトレーニングやメンテナンス方法を決めていきます。
      </p>
    </div>
    <div class="mainMiddle__2__concept mx-auto mt-5">
      <p class="m-0"><span>P</span>erformance</p>
      <p class="m-0"><span>T</span>uning</p>
      <p class="m-0"><span>P</span>otential</p>
      <div class="mainMiddle__2__concept--circle1 mx-auto circleCommon"></div>
      <div class="mainMiddle__2__concept--circle2 mx-auto circleCommon"></div>
      <div class="mainMiddle__2__concept--circle3 mx-auto circleCommon"></div>
    </div>
    <ul class="col-md-10 m-auto pb-5">
      <li>
        <strong>●Tuning</strong>
        <p class="pl-3">今のあなたに合った身体を整える施術をメインに動きやすい身体に導きます。</p>
      </li>
      <li>
        <strong>●Potential</strong>
        <p class="pl-3">今のあなたがまだ出し切れてない力を発揮できるトレーニングを指導いたします。</p>
      </li>
      <li>
        <strong>●Performance</strong>
        <p class="pl-3">スポーツであればより動きやすく、日常であればより楽に動けるようトレーニング指導いたします。</p>
      </li>
    </ul>
  </div>
  <!-- mainMiddle__3 view -->
  <div class="mainMiddle__3 pt-5" id="menuList">
    <h2 class="text-center my-5 font-weight-bold">＜Price＞</h2>
    <div class="mainMiddle__3__menu1 col-sm-10 m-auto d-sm-flex justify-content-between flex-wrap">
      <div class="mainMiddle__3__menu1--item d-flex justify-content-between mb-5 font-weight-bold mx-auto mx-md-0">
        <p>15分</p>
        <p>・・・・・・</p>
        <p>¥1,600</p>
      </div>
      <div class="mainMiddle__3__menu1--item d-flex justify-content-between mb-5 font-weight-bold mx-auto mx-md-0">
        <p>30分</p>
        <p>・・・・・・</p>
        <p>¥3,300</p>
      </div>
      <div class="mainMiddle__3__menu1--item d-flex justify-content-between mb-5 font-weight-bold mx-auto mx-md-0">
        <p>40分</p>
        <p>・・・・・・</p>
        <p>¥4,400</p>
      </div>
      <div class="mainMiddle__3__menu1--item d-flex justify-content-between mb-5 font-weight-bold mx-auto mx-md-0">
        <p>60分</p>
        <p>・・・・・・</p>
        <p>¥6,600</p>
      </div>
    </div>
    <div class="mainMiddle__3__menu2 col-md-10 font-weight-bold text-danger mx-auto text-center text-md-left">
      <p class="">★初めての方はこちら↓</p>
      <p>初回無料カウンセリング(20分)</p>
    </div>
    <div class="mainMiddle__3__image mx-auto mt-5">
      <%= image_tag "image4.jpg" %>
      <%= image_tag "image6.jpg" %>
      <%= image_tag "image10.jpg" %>
    </div>
  </div>
</div>

<div class="phoneSize__reserv pt-5 mx-sm-5" id="reserv">
  <p class="text-center font-weight-bold pt-5">＜ご予約はこちら↓＞</p>
  <iframe src="https://select-type.com/rsv/?id=i9Mcxd2ZDYk&w_flg=1" frameborder="0"></iframe>
</div>
  
<!-- footer view -->
<footer class="mt-5">
  <div class="footerContents d-sm-flex py-5">
    <div class="footerContents__left col-sm-6 text-center">
      <h3>＜Follow Us＞</h3>
      <p class="pt-3">
        SNS定期更新してます!!!<br>
        ご質問なども承っていますので是非みていって下さいね！
      </p>
      <%# <i class="fab fa-facebook p-3"></i>
      <i class="fab fa-instagram p-3"></i> %>
      
      <%= link_to "https://m.facebook.com/ari.onigiri?ref=bookmarks" do %>
        <%= icon("fab","facebook",class: "p-3 footerContents__left--icon")%>
      <% end %>
      <%= link_to "https://www.instagram.com/aa_ri_17/?hl=ja" do %>
        <%= icon("fab","instagram",class: "p-3 footerContents__left--icon")%>
      <% end %>

    </div>
    <div class="footerContents__right col-sm-6 text-center pt-5 pt-sm-0" id="contactForm">
      <h3>＜Contact Form＞</h3>
      <%= form_with url: home_inquiry_path do |f| %>
      <%#= form_for @inquiry, url: home_inquiry_path do |f| %>
        <div class="mb-3">
          <%= f.text_field :name, id: "contactForm__name", placeholder: "●お名前" %>
        </div>
        <div class="mb-3">
          <%= f.text_field :email, id: "contactForm__email", placeholder: "●Email" %>
        </div>
        <div>
          <%= f.text_area :message, name: "contactForm__message", value: inquiry_text %>
        </div>
        <%= f.submit '送信', class: "contactForm__submit d-none" %>
      <% end %>
      <button class="btn btn-primary" id="fonmConfirmBtn">確認</button>
    </div>
  </div>
  <div class="footerCopyRight text-center">
    ©︎ 2020 xxxxx All rights reserved.
  </div>
</footer>
<!-- formConfirm view -->
<div class="formConfirmModal d-none">
  <div class="formConfirmModal__text mx-auto mt-5 py-3 px-1 font-weight-bold">
    <h4 class="text-center font-weight-bold">＜送信内容の確認＞</h4>
    <p class="m-0">お名前：<span id="formConfirm__name" class="font-weight-light"></span></p>
    <p class="m-0">Email:<span id="formConfirm__email" class="font-weight-light"></span></p>
    <p class="m-0">お問い合わせ内容：</p>
    <p id="formConfirm__message" class="font-weight-light"></p>
    <div class="text-center">
      <p class="m-0">内容に問題がない↓</p>
      <button class="btn btn-primary mb-1 font-weight-bold" id="formConfirmModal__submit">送信する</button>
    </div>
    <div class="text-center">
      <p class="m-0">修正すべき箇所がある↓</p>
      <button class="btn btn-danger font-weight-bold" id="formConfirmModal__close">ホーム画面に戻る</button>
    </div>
  </div>
</div>
<!-- sending message view -->
<div class="sendingMessage d-none">
  <p class="mt-5 mx-auto text-danger font-weight-bold py-3 text-center">
    メッセージ送信中・・・<br>
    しばらくお待ちください。
  </p>
</div>

app/views/home/inquiry.html.erb
<%= form_for @inquiry, :url => home_inquiry_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
  </div>

  <table class="table">
    <tr>
      <th>名前<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message %></td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AriGym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="MRTとは、人生の生きがい。MRTとは、Moving Rejoice Trigger(動く、喜ぶ、キッカケ）を基盤にお客様一人一人に寄り添った個別パーソナルトレーナーです。" />
    <meta name="Keywords" content="MTR, 人生の生きがい, Moving Rejoice Trigger, 動く 喜ぶ キッカケ, 出張 23パーソナル, 出張 トレーナー, 出張 ジム, 出張 トレーニング" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>